### ISSUE TITLE
Install The CMS

### ISSUE THREAD

**Issue by vdanelia** [StudioJunkyard/LibreCMS#1]
Hello Does your CMS Supports Multilingual Content?

**Comment by StudioJunkyard** [comment]
Not at this time, but may be planned in the future. At the moment, it's targetted mostly to Australian Site.

**Comment by StudioJunkyard** [comment]
From the text in the email. There is no actual installer at this time at least. Look for "libre.sql" in the core/ folder. To login use admin/admin
