### ISSUE TITLE
Admin Login Problem

### ISSUE THREAD

**Issue by vdanelia** [StudioJunkyard/LibreCMS#2]
I Installed The CMS
Logged In but can't access the admin.php (Successfully Logged Front-end)
Displaying No errors just blank page and nothing more (also Added error_reporting (-1); )
What's wrong?
Please Help!

Testing On My Localhost
Options:
PHP: 5.5.12 Also 5.6.0 (With PDO)
MySQL: 5.5.38
Apache: 2.2.27
PHPMyAdmin: 4.2.7

mod_rewrite enabled

**Comment by StudioJunkyard** [comment]
take the .php off the url, the admin also uses mod_rewrite.

Also, be wary, there's still a lot being fixed, at present, so don't expect everything to work.

**Comment by vdanelia** [comment]
Ok Thanks :+1:

**Comment by StudioJunkyard** [comment]
Your welcome, and thanks for having a look at the CMS, ignore my paltry coding efforts :D
